print("Ruslan Fateev is cool!")
print("Ruslan Fateev is cool!")
print("Ruslan Fateev is cool!")
print("Ruslan Fateev is cool!")
print("Ruslan Fateev is cool!")
print("Ruslan Fateev is cool!")
print("Akim")
print("SONIIAAA")
